### ISSUE TITLE
User must able to set custom encryption key

### ISSUE THREAD

**Issue by bdshanto** [nixgram/crypto-browser-storage#12]
Feature 
- Injectable into service into `app.module.ts`
- Have to provide `init()` functionality for custom config

**Comment by sefatanam** [comment]
about to release soon !
finally 🎉

**Comment by sefatanam** [comment]
Now you can provide custom encryption key like this, 

```
providers: [
    ....
    CryptoBrowserStorageService,
    { provide: CRYPTO_HASH_KEY, useValue: 'YOUR_KEY_HERE' }
  ]
```

Package is published : https://www.npmjs.com/package/crypto-browser-storage?activeTab=readme 💪
